server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: 42.192.234.111:9092
    producer:
      #生产者key序列化方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #生产者value序列化方式
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      transaction-id-prefix: my_tx. #事务编号前缀
    consumer:
      #消费者组
      group-id: test-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      isolation-level: read_committed

kafka:
  topic:
    topic-test-transaction: topic-test-transaction
    topic-test-transaction2: topic-test-transaction2